### ISSUE TITLE
We need a more accessible translation server, possibly self-hosted and compatible with OFF account.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-translations#2]
http://pootle.translatehouse.org/ ?

**Comment by stephanegigandet** [comment]
If we want to provide SSO (using Open Food Facts authentication) on pootle:

http://docs.translatehouse.org/projects/pootle/en/stable-2.5.1/features/authentication.html

https://docs.djangoproject.com/fr/1.7/topics/auth/customizing/
